### ISSUE TITLE
[Fabric 1.20.1] Incompatible with Deeper and Darker

### ISSUE THREAD

**Issue by Dumpling00** [Frozeh/infinity-cave#13]
Deeper and Darker is a mod that extends the sculk region and makes it deeper.
Could Infinity cave work with this by making it so it can just spawn below it if present?

That would be amazing. Thank you for your time and consideration.

**Comment by Dumpling00** [comment]
Nevermind sorry, this was caused by another mod that in retrospect has been nothing but trouble. Got Infinity Caves to work!

**Comment by Frozeh** [comment]
Alright, thanks for reporting it anyways.
