### ISSUE TITLE
Xaero's Map is INCOMPATIBLE with Infinity Caves!

### ISSUE THREAD

**Issue by Boy17000** [Frozeh/infinity-cave#17]
Hi, as stated in the Title, If someone adds Infinity Cave to a already running server/world etc every Already loaded chunk which used to be normal looking on Xaero's minimap now have gone mad, and displayed only a stone surface as if it was in cave mode...

Seemingly the server height change caused the issue with Xaero's minimap.

**Comment by Frozeh** [comment]
I'd recommend using JourneyMap, I had no issues when using it, I'm not sure what causes Xaerno's minimap to not work properly

**Comment by CoNtrolV1** [comment]
I had the same problem, and when I realized this incompatibility, I tried to remove the mod, but once it was installed, I couldn't remove it because the world wouldn't open...

**Comment by Frozeh** [comment]
Go into Xaero's settings and enable `Ignore Server Heightmap` boot the server with Infinity Cave and it fixed the issue.
