### ISSUE TITLE
Lava spawning below y level -55

### ISSUE THREAD

**Issue by Adaptable1** [Frozeh/infinity-cave#18]
Using infinity caves 0.4 1.20.1 and it seems that lava spawns below -55 and filling up the caves, except for the cave biomes. Using Terralith and Terrablender world gen mods.

![image](https://github.com/user-attachments/assets/553acb4e-1bd9-431e-a90c-4753df79730c)
In the image above, only the non-biome infinite caves are filled with lava. 
![image](https://github.com/user-attachments/assets/48309e39-b80e-4103-ab59-4d549c1a8919)
All pockets of air that are below y -55, including caves that lead to the infinite caves, are getting replaced by lava.
Maybe it's a Minecraft generation bug? Since vanilla minecraft also spawns lava in all air pockets below y -55.
![image](https://github.com/user-attachments/assets/1c398a43-7732-4a7a-8218-804fca0d58b2)
Vanilla 1.20.1 also indicates that this might be a conflict with minecraft itself, since lava always spawns below y-55.

**Comment by Frozeh** [comment]
Fixed in recent version

**Comment by Paulem79** [comment]
occuring on 26.1
