### ISSUE TITLE
Datapack doesn't work for Bedrock players

### ISSUE THREAD

**Issue by Disueri** [Frozeh/infinity-cave#19]
Now, I know realistically that making the datapack work for Bedrock players isn't in the scope for your plans, or isn't even possible. However, on Minehut servers Bedrock and Java players can play together on the same server. I downloaded the 1.21.1 version and added it to the server, as a Java player I can enter it and play it as normal. My brother on the mobile version of Bedrock just falls through the Infinite Caves as if there's no blocks at all. I don't really expect there to be any fixes for such a hyper specific and small use case, but I thought I should report it just in case.

**Comment by Frozeh** [comment]
This is not an issue on my end, you'd have to ask people at Geyser. There is nothing I can do in this situation.
