### ISSUE TITLE
Feature: Retrogen for 1.20.1

### ISSUE THREAD

**Issue by LokeYourC3PH** [Frozeh/infinity-cave#2]
Hey there, love the mod and was looking for something like this!

So, I have a 1.20.1 modpack in which I want to retroactively generate this & change an already existing map. Is it possible to change existing maps to expand into y=-128 and move the bedrock layer as well? It seems to only work in chunks that have not been generated yet unfortunately.

**Comment by Frozeh** [comment]
Grab something like world edit. Copy your map (you may need to do this in parts), save it as a schematic, test if it works, leave world, remove the region files of the world, join the world, paste the schematic at the same spot where you copied it. Make sure to do /copy -e (this will copy entities as well), then /paste -e after loading the schematic. 

WorldEdit: https://modrinth.com/plugin/worldedit
Schematic: https://www.minecraft-schematics.com/worldedit/tutorial/

**Comment by LokeYourC3PH** [comment]
Way too complicated over just adding Retrogen like some mods do 😂 Also, my server isn't unmodded, so way too many things will break on an actively played on map. I also had to remove the mod anyways as it slowed down chunk generation by an incredible amount, so right now it's not really playable for us anyways.

Just keep the suggestion in mind 🙂

**Comment by Frozeh** [comment]
I'm sorry to hear that, but it isn't that complicated to do as world edit does support modded blocks, if world generation is slow, just pregenerate them. I have never heard of Retrogen until now, so I'll be sure to look into it, I'm just trying to find a solution to your problem.
