### ISSUE TITLE
Huge Huge Broken Chunks of Lava, Literal Minecraft Chunks

### ISSUE THREAD

**Issue by desagas** [Frozeh/infinity-cave#21]
![2024-09-12_09 47 13](https://github.com/user-attachments/assets/444eaa1c-c34e-4d70-9bcb-0cdadc707ca9)

If you look at my minimap, every single straight edge along a chunk line, with black behind it, is what you see in the image: a solid chink of lava, until the bottom layers of deepslate and bedrock. I am not sure if this is meant to happen, if so, I do not like this at all, but, the rest of it is okay so far. Just perfect square bordering chunks of lava seems way to unnatural for the game.

Using version 0.6, on Neo .51.

**Comment by Frozeh** [comment]
This is due to incompatibilities with other Minecraft worldgen mods that uses a high biome depth, I am working on solving this in the future, which mods are you using with Infinity Cave for the lava-filled caves to occur?

**Comment by desagas** [comment]
So, are you looking to the registry for biomes above, for determining your generation, rather than simply generating your own noise map? This method may be the reason for this bug? I believe you can access the biome distribution noise map through the registry, and just add on to it? But that may cause a similar issue to what we see. Or, you could create your own noise map, and then limit your generation to only between -64 and -128 Y, and add carvers to create access points between say -56 and -72, or something like that, in addition to your code that replaces bedrock with something else. Just an idea. This way, it doesn't matter what mod is where, it will just work.

Also, I am using many terrain mods, I believe this is all of the ones that add or control biomes and their generations:
- Terralith
- Deeper and Darker
- Gardens of the Dead
- TerraBlender
- Oh the Biomes We've Gone
- Biomes o Plenty
- Ars Nouveau

**Comment by desagas** [comment]
Also, some more information: the stone generation seems to work perfectly, as do the carvers at this level, although, I have only seen two of your biomes, the massive amethyst biome, and plain deep slate caves, but, they generate, and the lava only fills in the gaps within the carvers. So, in short, lava is only replacing air, not the entire chunk!

![2024-09-30_09 47 33](https://github.com/user-attachments/assets/d7ecd6f4-0a21-44b8-b8ca-0fa505897961)

**Comment by desagas** [comment]
If you want a second set of eyes, I would gladly look into your code. My mod dealt with world generation issues in 1.16.5, and was been downloaded a few million times. But, your code is not visible. My discord is 'desagas' and or added me as a collaborator or viewer or whatever on here. Just an offer, that is all.

**Comment by Frozeh** [comment]
It uses datapack functionality for worldgen, so it is a bit harder than that, I suppose I could make a dependency that removes the hardcoded lava, the issue lies in biome depth, most modded biomes add a large depth to their biomes making them generate all the way into Infinity Cave territory. Even if the caves generate, it does look quite bland. I have a few ideas on how to fix it, but I am very busy at the moment.

**Comment by Frozeh** [comment]
I have found a way to fix it, will address this in the next update.
