### ISSUE TITLE
Light Emblem Bug (?) [Fabric 1.20.1, datapack]

### ISSUE THREAD

**Issue by jajfxsudo** [Frozeh/infinity-cave#24]
I'm trying to use Light Emblems in a server and for some reason, sometimes they bug out and just become invisible armor stands (only viewable in spectator)

I haven't really dont anything crazy to fix it because it happens randomly and fixes "randomly" (I'm sure there's a reason it fixes but since I don't know it I just assume it's randomly) If you do know the issue pleasee help

It has properties to float, can't be destroyed, it's really weird it just exists and I don't know I assume /kill would be the only way to get it out, but since I'm not an admin I can't check

Originally an admin thought it was because of the y was above 56 (even though it wasn't) I tried it again at a lower Y level and it still just became a broken invisible armor stand
![image_2024-10-25_192323066](https://github.com/user-attachments/assets/aa1aea8f-673d-469c-8d38-aa3e48540035)
![image](https://github.com/user-attachments/assets/cf9b25ca-fb68-4577-9c2a-cb7507ac322f)

**Comment by Frozeh** [comment]
Oops, light emblems are not intended to be found in 1.20.1, I shall see if I can fix this later.
